### ISSUE TITLE
Gallery Not Working

### ISSUE THREAD

**Issue by JaiDoubleU** [realstoman/react-tailwindcss-portfolio#18]
Thank you for your work.  I notice all the projects in the gallery navigate to the same page showing the same details.  How do you envision we resolve this?

**Comment by realstoman** [comment]
Thank you @JaiDoubleU. There are multiple ways that you can have dynamic pages for the projects section using **React Router** and also **Server Side Props**, the same I did in the [Next.js version](https://github.com/realstoman/nextjs-tailwindcss-portfolio) of this project. For the gallery, there are multiple plugins you can use, or make a simple carousel using pure React and JavaScript.

**Comment by SubhamB2003** [comment]
Hey, I just checking your repository and found some issues on this site:-- 
1. You can use Lazy Loading to improve the performance of this site.
2. If I go to a different page and reload then the site show page not found error.
Can I add these 2 features to your site?

**Comment by realstoman** [comment]
Hey @SubhamB2003 , thank you for noticing the issues. Yes please, open a pull request that contains the changes. Thank you.
